server:
  port: 9002
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: mjyxy

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ykongl.maintain.bean

